=== falkon33/23_24-LEMA-PROYECTOXML-ALVAREZ/dtd/dnd.dtd
<!-- Define the root element "dnd" containing "characters" and "spels" -->
<!ELEMENT dnd (characters, spels)>
<!-- Define the "characters" element containing one or more "character" elements -->
<!ELEMENT characters (character+)>
<!-- Define the structure of an individual character -->
<!ELEMENT character (class+, race, ac, hitpoints, proficiencies, spell_slot?, stats, features, inventory, img,link)>
<!-- Define the attribute "level" for character with default value '1' -->
<!ATTLIST character level NMTOKEN '1'>
<!-- Define the required attribute "id" for character -->
<!ATTLIST character id ID #REQUIRED>
<!-- Define the "class" element containing "name" and optional "levels" -->
<!ELEMENT class (name+, levels?)>
<!-- Define the "name" element as parsed character data -->
<!ELEMENT name (#PCDATA)>
<!-- Define the "levels" element as parsed character data -->
<!ELEMENT levels (#PCDATA)>
<!-- Define elements for character attributes -->
<!ELEMENT race (#PCDATA)>
<!ELEMENT ac (#PCDATA)>
<!ELEMENT hitpoints (#PCDATA)>
<!ELEMENT proficiencies (armor, weapon, tool, saving_throw, skill)>
<!ELEMENT armor (#PCDATA)>
<!ELEMENT weapon (#PCDATA)>
<!ELEMENT tool (#PCDATA)>
<!ELEMENT saving_throw (#PCDATA)>
<!ELEMENT skill (#PCDATA)>
<!-- Define the optional "spell_slot" element with sub-elements for each spell level -->
<!ELEMENT spell_slot (lv1, lv2, lv3, lv4, lv5, lv6, lv7, lv8, lv9)>
<!ELEMENT lv1 (#PCDATA)>
<!ELEMENT lv2 (#PCDATA)>
<!ELEMENT lv3 (#PCDATA)>
<!ELEMENT lv4 (#PCDATA)>
<!ELEMENT lv5 (#PCDATA)>
<!ELEMENT lv6 (#PCDATA)>
<!ELEMENT lv7 (#PCDATA)>
<!ELEMENT lv8 (#PCDATA)>
<!ELEMENT lv9 (#PCDATA)>
<!-- Define the "stats" element containing attributes for various statistics -->
<!ELEMENT stats (str, dex, con, int, wis, cha)>
<!ELEMENT str (#PCDATA)>
<!ELEMENT dex (#PCDATA)>
<!ELEMENT con (#PCDATA)>
<!ELEMENT int (#PCDATA)>
<!ELEMENT wis (#PCDATA)>
<!ELEMENT cha (#PCDATA)>
<!-- Define the "features" element containing one or more "feature" elements -->
<!ELEMENT features (feature+)>
<!ELEMENT feature (#PCDATA)>
<!-- Define the "inventory" element containing zero or more "item" elements -->
<!ELEMENT inventory (item*)>
<!ELEMENT item (#PCDATA)>
<!-- Define the "img" element as parsed character data -->
<!ELEMENT img (#PCDATA)>
<!-- Define the "link" element as parsed character data -->
<!ELEMENT link (#PCDATA)>
<!-- Define the "spels" element containing one or more "spell" elements -->
<!ELEMENT spels (spell+)>
<!-- Define the "spell" element with attributes and sub-elements -->
<!ELEMENT spell (name, class, tags, cast, desc, price,link)>
<!ATTLIST spell school NMTOKEN #IMPLIED>
<!ATTLIST spell id ID #REQUIRED>
<!ELEMENT tags (tag*)>
<!ELEMENT tag (#PCDATA)>
<!ELEMENT cast (#PCDATA)>
<!ELEMENT desc (#PCDATA)>
<!ELEMENT price (#PCDATA)>

=== falkon33/23_24-LEMA-PROYECTOXML-ALVAREZ/xml/dnd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dnd SYSTEM "../dtd/dnd.dtd">
<?xml-model href="../xsd/dnd.xsd"?>
<dnd>
    <!-- personajes -->
    <characters>
        <!-- nivel -->
        <character level="1" id="b1">
            <!-- clases -->
            <class>
                <name>Barbarian</name>
                <levels>1</levels>
            </class>
            <!-- datos basicos -->
            <race>Human</race>
            <ac>13</ac>
            <hitpoints>15</hitpoints>
            <!-- competencias -->
            <proficiencies>
                <armor>ligth, medium, shield</armor>
                <weapon>martial, simple</weapon>
                <tool>no</tool>
                <saving_throw>str, con</saving_throw>
                <skill>athletic, deception, insight, survival</skill>
            </proficiencies>
            <!-- puntuaciones de caracteristicas -->
            <stats>
                <str>16</str>
                <dex>11</dex>
                <con>16</con>
                <int>10</int>
                <wis>14</wis>
                <cha>10</cha>
            </stats>
            <features>
                <!-- dotes -->
                <feature>Rage: In battle, you fight with primal ferocity. On your turn, you can
                    enter a rage as a bonus action. While raging, you gain the following benefits if
                    you aren’t wearing heavy armor: -You have advantage on Strength checks and
                    Strength saving throws. -When you make a melee weapon attack using Strength, you
                    gain a bonus to the damage roll that increases as you gain levels as a
                    barbarian, as shown in the Rage Damage column of the Barbarian table. -You have
                    resistance to bludgeoning, piercing, and slashing damage. If you are able to
                    cast spells, you can’t cast them or concentrate on them while raging. Your rage
                    lasts for 1 minute. It ends early if you are knocked unconscious or if your turn
                    ends and you haven’t attacked a hostile creature since your last turn or taken
                    damage since then. You can also end your rage on your turn as a bonus action.
                    Once you have raged the number of times shown for your barbarian level in the
                    Rages column of the Barbarian table, you must finish a long rest before you can
                    rage again.</feature>
                <feature>Unarmored defense: While you are not wearing any armor, your Armor⁠ Class
                    equals 10 + your Dexterity modifier + your Constitution modifier. You can use a
                    shield and still gain this benefit.</feature>
            </features>
            <inventory>
                <!-- objetos -->
                <item>Battleaxe</item>
                <item>Handaxe</item>
                <item>Explorer's Pack</item>
                <item>Javelin</item>
                <item>Backpack</item>
                <item>Bedroll</item>
                <item>Mess Kit</item>
                <item>Tinderbox</item>
                <item>Torch</item>
                <item>Ration</item>
                <item>Waterskin</item>
                <item>Hempen Rope</item>
            </inventory>
            <!-- imagen -->
            <img>barbarian</img>
            <link>https://https://www.dndbeyond.com/classes/barbarian</link>
        </character>
        <!-- nivel -->
        <character level="4" id="b2">
            <!-- clases -->
            <class>
                <name>Warlock</name>
                <levels>2</levels>
            </class>
            <class>
                <name>Sorcerer</name>
                <levels>2</levels>
            </class>
            <!-- datos basicos -->
            <race>Tiefling</race>
            <ac>13</ac>
            <hitpoints>19</hitpoints>
            <!-- competencias -->
            <proficiencies>
                <armor>ligth</armor>
                <weapon>simple</weapon>
                <tool>no</tool>
                <saving_throw>wis, cha</saving_throw>
                <skill>deception, insight, intimidation, religion</skill>
            </proficiencies>
            <!-- espacios de conjuro -->
            <spell_slot>
                <lv1>5</lv1>
                <lv2>0</lv2>
                <lv3>0</lv3>
                <lv4>0</lv4>
                <lv5>0</lv5>
                <lv6>0</lv6>
                <lv7>0</lv7>
                <lv8>0</lv8>
                <lv9>0</lv9>
            </spell_slot>
            <!-- puntuaciones de caracteristicas -->
            <stats>
                <str>8</str>
                <dex>15</dex>
                <con>8</con>
                <int>9</int>
                <wis>15</wis>
                <cha>17</cha>
            </stats>
            <!-- dotes -->
            <features>
                <feature>Dark One's Blessing: Starting at 1st level, when you reduce a hostile
                    creature to 0 hit points, you gain temporary hit points equal to your Charisma
                    modifier + your warlock level (minimum of 1).</feature>
                <feature>Hellish Resistance: You have resistance to fire damage.</feature>
                <feature>Darkvision: Thanks to your infernal heritage, you have superior vision in
                    dark and dim conditions. You can see in dim light within 60 feet of you as if it
                    were bright light, and in darkness as if it were dim light. You can't discern
                    color in darkness, only shades of gray.</feature>
                <feature>Eldritch Invocations: In your study of occult lore, you have unearthed
                    eldritch invocations, fragments of forbidden knowledge that imbue you with an
                    abiding magical ability. At 2nd level, you gain two eldritch invocations of your
                    choice. Your invocation options are detailed at the end of the class
                    description. When you gain certain warlock levels, you gain additional
                    invocations of your choice, as shown in the Invocations Known column of the
                    Warlock table. Additionally, when you gain a level in this class, you can choose
                    one of the invocations you know and replace it with another invocation that you
                    could learn at that level.</feature>
                <feature>Eldritch Invocation: Agonizing Blast: When you cast eldritch blast, add
                    your Charisma modifier to the damage it deals on a hit.</feature>
                <feature>Eldritch Invocation: Repelling Blast: When you hit a creature with eldritch
                    blast, you can push the creature up to 10 feet away from you in a straight line.</feature>
                <feature>Sorcery Points: At 2nd level, you tap into a deep wellspring of magic
                    within yourself. This wellspring is represented by sorcery points, which allow
                    you to create a variety of magical effects. You have 2 sorcery points, and you
                    gain more as you reach higher levels, as shown in the Sorcery Points column of
                    the Sorcerer table. You can never have more sorcery points than shown on the
                    table for your level. You regain all spent sorcery points when you finish a long
                    rest.</feature>
                <feature>Flexible Casting: You can use your sorcery points to gain additional spell
                    slots, or sacrifice spell slots to gain additional sorcery points. You learn
                    other ways to use your sorcery points as you reach higher levels. Creating Spell
                    Slots. You can transform unexpended sorcery points into one spell slot as a
                    bonus action on your turn. The Creating Spell Slots table shows the cost of
                    creating a spell slot of a given level. You can create spell slots no higher in
                    level than 5th. A 1st level Spell Slot cost 2 Sorcery Points A 2nd level Spell
                    Slot cost 3 Sorcery Points A 3rd level Spell Slot cost 5 Sorcery Points A 4th
                    level Spell Slot cost 6 Sorcery Points A 5th level Spell Slot cost 7 Sorcery
                    Points Converting a Spell Slot to Sorcery Points. As a bonus action on your
                    turn, you can expend one spell slot and gain a number of sorcery points equal to
                    the slot’s level.</feature>
                <feature>Flexible Casting: You can use your sorcery points to gain additional spell
                    slots, or sacrifice spell slots to gain additional sorcery points. You learn
                    other ways to use your sorcery points as you reach higher levels. Creating Spell
                    Slots. You can transform unexpended sorcery points into one spell slot as a
                    bonus action on your turn. The Creating Spell Slots table shows the cost of
                    creating a spell slot of a given level. You can create spell slots no higher in
                    level than 5th. A 1st level Spell Slot cost 2 Sorcery Points A 2nd level Spell
                    Slot cost 3 Sorcery Points A 3rd level Spell Slot cost 5 Sorcery Points A 4th
                    level Spell Slot cost 6 Sorcery Points A 5th level Spell Slot cost 7 Sorcery
                    Points Converting a Spell Slot to Sorcery Points. As a bonus action on your
                    turn, you can expend one spell slot and gain a number of sorcery points equal to
                    the slot’s level.</feature>
